### ISSUE TITLE
Add 'einops' to requirements.txt

### ISSUE THREAD

**Issue by songyuc** [qingqing-zijin/LEAD-YOLO#6]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear developers,

I'm writing to report an issue I encountered while attempting to run the LEAD - YOLO project. When I executed the `python detect.py --weights "./weights/lead_yolo(ssdd).pt" --data./data/SSDD.yaml --source./source` command, I got the following error:
```
Traceback (most recent call last):
  File "/home/[USERNAME]/LEAD-YOLO/detect.py", line 45, in <module>
    from models.common import DetectMultiBackend
  File "/home/[USERNAME]/LEAD-YOLO/models/common.py", line 1168, in <module>
    from einops import rearrange, reduce
ModuleNotFoundError: No module named 'einops'
```

Evidently, the project relies on the 'einops' library, but it's absent from the `requirements.txt` file. This omission poses a challenge for new users aiming to set up the proper environment and replicate the project's functionality smoothly.

I understand that such oversights can occur during development. If it's convenient for you, I'm eager to contribute by submitting a pull request (PR) to incorporate 'einops' into the `requirements.txt` file. I'm certain this minor tweak will improve the overall user experience and render the project more accessible to the community.

Thank you for your dedication to this outstanding project. I'm looking forward to your response.

Best regards,
Eric

**Comment by qingqing-zijin** [comment]
Dear Eric,

Thank you for taking the time to report this issue and for your thoughtful suggestion! You are absolutely correct — the einops library should be included in the requirements.txt file, as it is a key dependency for running the project successfully.

We appreciate your initiative and willingness to contribute. Please feel free to submit a pull request (PR) to add einops to the requirements.txt file. Your contribution will undoubtedly help other users set up the environment more smoothly and enhance the overall user experience.

If you have any questions during the PR submission process, don’t hesitate to reach out. We look forward to reviewing your PR and collaborating with you.

Best regards,
MoHao
LEAD-YOLO Team

**Comment by songyuc** [comment]
Thanks sincerely for your guide!
